import type { AccountingDocument } from "./types";

export const mockDocuments: AccountingDocument[] = [
  {
    id: "doc-001",
    documentType: "invoice",
    status: "NeedsReview",
    vendorName: "サンプル広告株式会社",
    invoiceNumber: "INV-2026-001",
    registrationNumber: "",
    issueDate: "2026-05-01",
    dueDate: "2026-05-31",
    subtotal: 100000,
    taxAmount: 10000,
    totalAmount: 110000,
    taxRate: 0.1,
    confidenceScore: 0.86,
    fileStoragePath: "sample-ads-2026-05.pdf",
    fileMediaType: "application/pdf",
    fileName: "sample-ads-2026-05.pdf",
    memo: "広告配信費のサンプル証憑",
    updatedAt: "2026-05-06T09:20:00+09:00",
    lines: [
      {
        id: "line-001",
        description: "Web広告運用費",
        quantity: 1,
        unitPrice: 100000,
        amount: 100000,
        taxRate: 0.1,
        confidenceScore: 0.88,
      },
    ],
    journalEntry: {
      id: "journal-001",
      debitAccount: "広告宣伝費",
      debitAmount: 110000,
      debitTaxCategory: "課税仕入10%",
      creditAccount: "未払金",
      creditAmount: 110000,
      creditTaxCategory: "対象外",
      department: "マーケティング",
      description: "Web広告運用費",
      aiReason: "取引先名と明細に広告運用費を示す語句が含まれているため、広告宣伝費を候補としました。",
      confidenceScore: 0.82,
    },
    warnings: [
      {
        id: "warning-001",
        warningType: "high_amount",
        severity: "warning",
        message: "10万円以上の支出です。承認者による確認が必要です。",
        status: "open",
      },
      {
        id: "warning-002",
        warningType: "missing_registration_number",
        severity: "warning",
        message: "インボイス登録番号が確認できません。必要に応じて取引先情報を確認してください。",
        status: "open",
      },
    ],
    auditLogs: [
      {
        id: "audit-001",
        actorType: "ai",
        actorName: "AI抽出",
        action: "項目抽出",
        fieldName: "vendorName",
        oldValue: "",
        newValue: "サンプル広告株式会社",
        createdAt: "2026-05-06T09:12:00+09:00",
      },
      {
        id: "audit-002",
        actorType: "ai",
        actorName: "AI仕訳候補",
        action: "仕訳候補生成",
        fieldName: "debitAccount",
        oldValue: "",
        newValue: "広告宣伝費",
        createdAt: "2026-05-06T09:13:00+09:00",
      },
    ],
  },
  {
    id: "doc-002",
    documentType: "invoice",
    status: "Reviewed",
    vendorName: "サンプルクラウド株式会社",
    invoiceNumber: "SC-2026-042",
    registrationNumber: "T1234567890123",
    issueDate: "2026-05-02",
    dueDate: "2026-05-20",
    subtotal: 38909,
    taxAmount: 3891,
    totalAmount: 42800,
    taxRate: 0.1,
    confidenceScore: 0.91,
    fileStoragePath: "sample-cloud-2026-05.pdf",
    fileMediaType: "application/pdf",
    fileName: "sample-cloud-2026-05.pdf",
    memo: "ホスティング費用",
    updatedAt: "2026-05-06T10:05:00+09:00",
    lines: [
      {
        id: "line-002",
        description: "クラウド基盤利用料",
        quantity: 1,
        unitPrice: 38909,
        amount: 38909,
        taxRate: 0.1,
        confidenceScore: 0.93,
      },
    ],
    journalEntry: {
      id: "journal-002",
      debitAccount: "通信費",
      debitAmount: 42800,
      debitTaxCategory: "課税仕入10%",
      creditAccount: "未払金",
      creditAmount: 42800,
      creditTaxCategory: "対象外",
      department: "エンジニアリング",
      description: "クラウド基盤利用料",
      aiReason: "クラウドホスティング利用料のため、通信費を候補としました。",
      confidenceScore: 0.78,
    },
    warnings: [],
    auditLogs: [
      {
        id: "audit-003",
        actorType: "user",
        actorName: "経理担当",
        action: "レビュー完了",
        fieldName: "status",
        oldValue: "NeedsReview",
        newValue: "Reviewed",
        createdAt: "2026-05-06T10:05:00+09:00",
      },
    ],
  },
  {
    id: "doc-003",
    documentType: "receipt",
    status: "PendingApproval",
    vendorName: "サンプルワークスペース株式会社",
    invoiceNumber: "SW-2026-019",
    registrationNumber: "T9876543210987",
    issueDate: "2026-05-03",
    dueDate: "2026-05-18",
    subtotal: 18000,
    taxAmount: 1800,
    totalAmount: 19800,
    taxRate: 0.1,
    confidenceScore: 0.89,
    fileStoragePath: "sample-workspace-2026-05.png",
    fileMediaType: "image/png",
    fileName: "sample-workspace-2026-05.png",
    memo: "チーム利用料",
    updatedAt: "2026-05-06T11:40:00+09:00",
    lines: [
      {
        id: "line-003",
        description: "チームワークスペース利用料",
        quantity: 1,
        unitPrice: 18000,
        amount: 18000,
        taxRate: 0.1,
        confidenceScore: 0.9,
      },
    ],
    journalEntry: {
      id: "journal-003",
      debitAccount: "支払手数料",
      debitAmount: 19800,
      debitTaxCategory: "課税仕入10%",
      creditAccount: "未払金",
      creditAmount: 19800,
      creditTaxCategory: "対象外",
      department: "オペレーション",
      description: "チームワークスペース利用料",
      aiReason: "SaaS利用料のため、支払手数料を候補としました。",
      confidenceScore: 0.74,
    },
    approval: {
      id: "approval-001",
      approverName: "承認者",
      status: "pending",
      comment: "月次SaaS費用の確認依頼です。",
      requestedAt: "2026-05-06T11:40:00+09:00",
    },
    warnings: [],
    auditLogs: [
      {
        id: "audit-004",
        actorType: "user",
        actorName: "経理担当",
        action: "承認依頼",
        fieldName: "status",
        oldValue: "Reviewed",
        newValue: "PendingApproval",
        createdAt: "2026-05-06T11:40:00+09:00",
      },
    ],
  },
  {
    id: "doc-004",
    documentType: "receipt",
    status: "Approved",
    vendorName: "サンプル交通株式会社",
    invoiceNumber: "TR-2026-003",
    registrationNumber: "T1111222233334",
    issueDate: "2026-05-04",
    dueDate: "2026-05-04",
    subtotal: 3273,
    taxAmount: 327,
    totalAmount: 3600,
    taxRate: 0.1,
    confidenceScore: 0.94,
    fileStoragePath: "sample-transport-2026-05.jpg",
    fileMediaType: "image/jpeg",
    fileName: "sample-transport-2026-05.jpg",
    memo: "顧客訪問交通費",
    updatedAt: "2026-05-06T12:10:00+09:00",
    lines: [
      {
        id: "line-004",
        description: "電車運賃",
        quantity: 1,
        unitPrice: 3273,
        amount: 3273,
        taxRate: 0.1,
        confidenceScore: 0.92,
      },
    ],
    journalEntry: {
      id: "journal-004",
      debitAccount: "旅費交通費",
      debitAmount: 3600,
      debitTaxCategory: "課税仕入10%",
      creditAccount: "未払金",
      creditAmount: 3600,
      creditTaxCategory: "対象外",
      department: "営業",
      description: "電車運賃",
      aiReason: "交通機関の利用を示す明細のため、旅費交通費を候補としました。",
      confidenceScore: 0.87,
    },
    warnings: [],
    auditLogs: [
      {
        id: "audit-005",
        actorType: "user",
        actorName: "承認者",
        action: "承認",
        fieldName: "status",
        oldValue: "PendingApproval",
        newValue: "Approved",
        createdAt: "2026-05-06T12:10:00+09:00",
      },
    ],
  },
];

export function getMockDocument(id: string) {
  return mockDocuments.find((document) => document.id === id);
}
